// Workflow dispatcher: render inputs, inject gcit_run_id, fire
// `POST /repos/{owner}/{repo}/actions/workflows/{wf}/dispatches`
// behind the per-credential rate bucket and the rate-limit
// snapshot.
//
// Behaviour:
//   - dispatcher fires workflow_dispatch via octocrab and hands the
//     gcit_run_id to the correlator (in `correlator.rs`).
//   - backoff via backon ExponentialBuilder
//     (min=5s, max=5m, factor=2.0, jitter=true).
//   - only fine-grained PATs are supported; the dispatcher's
//     `Client` is constructed via Client::builder which enforces
//     the prefix.
//
// Inputs:
//   - render every value in `inputs: BTreeMap<String, String>` via
//     handlebars (strict_mode + namespaced variables) using the
//     trigger event's `RunContext` as the data context.
//   - inject `gcit_run_id` -> the UUID v4 the caller generated.
//
// Rate-limit guard:
//   1. consult RateLimitState — if `should_defer` returns Some,
//      sleep for that duration before retrying.
//   2. acquire the per-credential RateBucket (pacing for non-quota
//      reasons — see rate_bucket.rs comment).
//   3. fire the request behind tokio::time::timeout.
//   4. opportunistically observe response headers regardless of
//      success/failure (RateLimitState::observe_headers).
//
// Retry: errors classified as Transient drive backon's exponential
// schedule. RateLimited carries `retry_after`; the loop sleeps for
// that duration before the next attempt rather than relying on
// backon's schedule alone.
//
// The actual run-id resolution is in `correlator.rs`. This
// dispatcher returns the `gcit_run_id` (Uuid) and the wall-clock
// `dispatched_at` so the correlator can match on `Run.name` and
// fall back to `head_sha + ?created>=dispatched_at`.

use std::collections::BTreeMap;
use std::sync::Arc;
use std::time::Duration;

use backon::{ExponentialBuilder, Retryable};
use chrono::{DateTime, Utc};
use serde_json::Value as JsonValue;
use tokio::time::timeout;
use tokio_util::sync::CancellationToken;
use tracing::{debug, instrument, warn};
use uuid::Uuid;

use super::client::Client;
use super::error::{classify, timeout_error, GithubErrorKind};
use super::rate_limit::RateLimitState;
use crate::git::rate_bucket::RateBucket;

/// Reserved input key gcit injects on every dispatch. The
/// workflow author MUST declare a matching input on
/// `on.workflow_dispatch.inputs.gcit_run_id`. Otherwise GitHub returns
/// 422 with "Unexpected inputs" which the classifier surfaces as
/// `DispatchInvalid` carrying a copy-paste YAML fix.
pub const GCIT_RUN_ID_INPUT: &str = "gcit_run_id";

/// Outcome of a successful dispatch — the supervisor hands these
/// to the correlator to find the resulting `Run.id` on GitHub.
#[derive(Debug, Clone)]
pub struct DispatchOutcome {
    /// UUID injected into the dispatch payload's `inputs.gcit_run_id`.
    /// The workflow's `run-name` directive copies this into
    /// `Run.name` so the correlator can match by substring.
    pub gcit_run_id: Uuid,
    /// Wall-clock instant the dispatch request was sent. Used by
    /// the correlator's fallback path
    /// (head_sha + ?created>=dispatched_at).
    pub dispatched_at: DateTime<Utc>,
    /// Repo (owner/repo). Carried for correlator + state updates.
    pub repo: String,
    /// Workflow filename (e.g. ci.yml). Carried for correlator.
    pub workflow: String,
    /// Ref the dispatch targeted (e.g. refs/heads/main). Carried
    /// for correlator + RunContext construction.
    pub ref_name: String,
}

/// Per-call dispatch parameters. Owned by the supervisor and built
/// from FlowConfig + RunContext at trigger time.
///
/// `gcit_run_id` is generated by the caller (the flow-layer
/// dispatcher) BEFORE rendering inputs so the same UUID surfaces in
/// `{{gcit.run_id}}` template renders AND in the dispatch payload's
/// injected `gcit_run_id` input. A UUID generated inside this module
/// would diverge from the one the caller used to build the
/// trigger-time RunContext, leaving notifier templates with
/// `Uuid::nil()` while the workflow saw a real value.
#[derive(Debug, Clone)]
pub struct DispatchParams {
    pub repo: String,
    pub workflow: String,
    pub ref_name: String,
    /// Caller-generated correlation id. Injected into the dispatch
    /// payload as `inputs.gcit_run_id`; surfaced via the
    /// `{{gcit.run_id}}` template namespace upstream.
    pub gcit_run_id: Uuid,
    /// Pre-rendered input map. The supervisor renders templates
    /// against the trigger's RunContext before calling
    /// `dispatch()` (so this module is free of handlebars deps —
    /// rendering is a single shared helper, see
    /// `render_inputs` below).
    pub rendered_inputs: BTreeMap<String, String>,
}

/// Render `templated_inputs` using the supplied handlebars context.
/// Returns the rendered map. Errors short-circuit on the first
/// template that fails to render (rare — config validation already
/// compiled every template against a probe context).
///
/// Lives here because the dispatcher is the only gcit module that
/// renders inputs (Discord/mail render their own templates inside
/// the notifier crates). Extracting it into a shared helper would
/// fragment without simplifying.
pub fn render_inputs<C: serde::Serialize>(
    templated_inputs: &BTreeMap<String, String>,
    ctx: &C,
    handlebars: &handlebars::Handlebars<'_>,
) -> Result<BTreeMap<String, String>, handlebars::RenderError> {
    let mut out = BTreeMap::new();
    for (k, v) in templated_inputs {
        let rendered = handlebars.render_template(v, ctx)?;
        out.insert(k.clone(), rendered);
    }
    Ok(out)
}

/// Build the JSON payload an octocrab `WorkflowDispatchBuilder.inputs`
/// expects: a `Value::Object` carrying every rendered input plus the
/// injected `gcit_run_id`. Pure-data helper so tests can inspect the
/// payload without contacting wiremock.
pub fn build_inputs_payload(
    rendered_inputs: &BTreeMap<String, String>,
    gcit_run_id: Uuid,
) -> JsonValue {
    let mut map = serde_json::Map::with_capacity(rendered_inputs.len() + 1);
    for (k, v) in rendered_inputs {
        map.insert(k.clone(), JsonValue::String(v.clone()));
    }
    // Injection is unconditional: the workflow author opts in by
    // declaring the matching input + run-name directive. If they do
    // NOT declare it, GitHub returns 422 and the classifier surfaces
    // DispatchInvalid with the YAML fix.
    // A user-supplied `gcit_run_id` key would be overwritten here;
    // config validation rejects user-supplied `gcit_run_id` keys
    // upstream so this overwrite is unreachable in practice.
    map.insert(
        GCIT_RUN_ID_INPUT.to_string(),
        JsonValue::String(gcit_run_id.to_string()),
    );
    JsonValue::Object(map)
}

/// Split `owner/repo` into `(owner, repo)`. Config validation
/// already enforces "exactly one '/'", so this is infallible in
/// practice; we still guard with a Result to surface the rare
/// case where state was hand-edited or fixtures are wrong.
pub fn split_repo(slash_form: &str) -> Result<(&str, &str), GithubErrorKind> {
    let mut parts = slash_form.splitn(2, '/');
    let owner = parts.next().unwrap_or("");
    let repo = parts.next().unwrap_or("");
    if owner.is_empty() || repo.is_empty() {
        return Err(GithubErrorKind::Unknown {
            source: anyhow::anyhow!(
                "repo `{slash_form}` must be `owner/repo` (config validation should have caught this)",
            ),
        });
    }
    Ok((owner, repo))
}

/// Fire one `workflow_dispatch` call. Returns the gcit_run_id +
/// wall-clock so the correlator can find the resulting run.
///
/// Pipeline:
///   1. Consult rate-limit snapshot; defer if no headroom.
///   2. Acquire per-credential RateBucket (pacing).
///   3. Inject `gcit_run_id` into the rendered input map.
///   4. Fire `POST .../actions/workflows/{wf}/dispatches` behind
///      tokio::time::timeout.
///   5. Classify any error via `super::error::classify`.
///
/// `#[instrument(skip(client, ...))]`: tracing hides the credential
/// (already redacted by `Client`'s impl) AND the rate buckets +
/// state objects (no sensitive data, but log spam isn't useful).
/// The credential ID name surfaces via `client.credential()` if
/// the dispatch fails (carried in `GithubErrorKind`).
#[instrument(level = "debug", skip(client, rate_bucket, rate_limit, params, cancel))]
pub async fn dispatch(
    client: &Client,
    rate_bucket: &RateBucket,
    rate_limit: &RateLimitState,
    params: &DispatchParams,
    cancel: &CancellationToken,
) -> Result<DispatchOutcome, GithubErrorKind> {
    let (owner, repo) = split_repo(&params.repo)?;

    wait_for_rate_limit_or_cancel(rate_limit, cancel).await?;

    // Pacing gate: per-credential min-interval bucket so flows
    // sharing one credential don't gang up at the same instant.
    rate_bucket.acquire().await;

    // Caller-generated correlation id. The flow layer generates the
    // UUID before rendering inputs so the same value surfaces in
    // `{{gcit.run_id}}` template renders and in the dispatch payload.
    let gcit_run_id = params.gcit_run_id;
    let dispatched_at = Utc::now();
    let payload = build_inputs_payload(&params.rendered_inputs, gcit_run_id);

    debug!(
        gcit_run_id = %gcit_run_id,
        repo = %params.repo,
        workflow = %params.workflow,
        ref_name = %params.ref_name,
        "dispatching workflow",
    );

    let route_uri = build_dispatch_uri(owner, repo, &params.workflow)?;
    let body = serde_json::json!({
        "ref": params.ref_name,
        "inputs": payload,
    });
    let response = send_dispatch_request(client, route_uri, &body, params, rate_limit).await?;

    // Refresh the rate-limit snapshot from response headers before
    // checking status. Even on error responses GitHub sets
    // X-RateLimit-*; observe before consuming.
    rate_limit.observe_headers(response.headers()).await;

    classify_response_or_error(response, client, params, rate_limit).await?;

    Ok(DispatchOutcome {
        gcit_run_id,
        dispatched_at,
        repo: params.repo.clone(),
        workflow: params.workflow.clone(),
        ref_name: params.ref_name.clone(),
    })
}

/// Quota gate: defer when the snapshot says we have no headroom.
/// The defer wait can stretch up to the full GitHub primary
/// rate-limit window (5000 req/h means resets land 60 minutes apart
/// in the worst case). Races against `cancel` so a SIGTERM or
/// per-flow reload during the wait does not block the dispatcher
/// thread for an hour.
async fn wait_for_rate_limit_or_cancel(
    rate_limit: &RateLimitState,
    cancel: &CancellationToken,
) -> Result<(), GithubErrorKind> {
    let Some(wait) = rate_limit.should_defer().await else {
        return Ok(());
    };
    debug!(?wait, "rate-limit snapshot says defer");
    tokio::select! {
        _ = cancel.cancelled() => Err(GithubErrorKind::Cancelled),
        _ = tokio::time::sleep(wait) => Ok(()),
    }
}

/// Build the workflow_dispatch route URI:
/// `/repos/{owner}/{repo}/actions/workflows/{workflow}/dispatches`.
fn build_dispatch_uri(
    owner: &str,
    repo: &str,
    workflow: &str,
) -> Result<http::Uri, GithubErrorKind> {
    let route = format!("/repos/{owner}/{repo}/actions/workflows/{workflow}/dispatches");
    route
        .parse::<http::Uri>()
        .map_err(|e| GithubErrorKind::Unknown {
            source: anyhow::anyhow!("dispatcher route URI invalid: {e}"),
        })
}

/// Fire the workflow_dispatch via octocrab's low-level `_post` so
/// response headers stay accessible (the high-level
/// WorkflowDispatchBuilder discards them on success). Wraps the
/// request in `tokio::time::timeout` so a stalled upstream doesn't
/// outlast `client.request_timeout()`.
async fn send_dispatch_request(
    client: &Client,
    route_uri: http::Uri,
    body: &serde_json::Value,
    params: &DispatchParams,
    rate_limit: &RateLimitState,
) -> Result<
    http::Response<http_body_util::combinators::BoxBody<bytes::Bytes, octocrab::Error>>,
    GithubErrorKind,
> {
    let send_fut = async { client.octocrab()._post(route_uri, Some(body)).await };
    match timeout(client.request_timeout(), send_fut).await {
        Ok(Ok(r)) => Ok(r),
        Ok(Err(e)) => {
            let classified = classify(
                e,
                client.credential(),
                &params.repo,
                &params.workflow,
                None,
                None,
            );
            Err(reclassify_403_via_snapshot(classified, rate_limit).await)
        }
        Err(_elapsed) => Err(timeout_error(client.request_timeout())),
    }
}

/// Map non-success status onto `GithubErrorKind`. Uses octocrab's
/// `map_github_error` to deserialize the structured error body, then
/// routes through `classify` + the 403-via-snapshot reclassifier.
async fn classify_response_or_error(
    response: http::Response<http_body_util::combinators::BoxBody<bytes::Bytes, octocrab::Error>>,
    client: &Client,
    params: &DispatchParams,
    rate_limit: &RateLimitState,
) -> Result<(), GithubErrorKind> {
    if response.status().is_success() {
        return Ok(());
    }
    // Re-extract status before consuming the response so we have it
    // for the classify step if octocrab's body parser fails.
    let status = response.status();
    match octocrab::map_github_error(response).await {
        Ok(_) => unreachable!("non-success response cannot map_github_error to Ok"),
        Err(e) => {
            let classified = classify(
                e,
                client.credential(),
                &params.repo,
                &params.workflow,
                None,
                None,
            );
            debug!(?status, "dispatch failed; classified error returned");
            Err(reclassify_403_via_snapshot(classified, rate_limit).await)
        }
    }
}

/// If `classify` returned `Forbidden` AND the rate-limit snapshot
/// says quota is exhausted (`remaining == 0`), reclassify as
/// `RateLimited`. When the dispatcher hits a 403, octocrab's
/// high-level builder doesn't expose the response headers, so the
/// classifier can't see `X-RateLimit-Remaining: 0` directly. The
/// poller-maintained snapshot is the authoritative answer — if it
/// says quota is gone, the 403 is rate-limited, not scope-denied.
///
/// When `remaining == Some(0)` but `reset` is missing or already in
/// the past (snapshot reset epoch was for the previous quota window),
/// default to one minute out so the dispatcher backs off rather than
/// treating the 403 as a permanent scope denial. Mirrors the
/// `classify_status` 403/Remaining=0/no-Reset fallback in
/// `github::error`.
async fn reclassify_403_via_snapshot(
    classified: GithubErrorKind,
    rate_limit: &RateLimitState,
) -> GithubErrorKind {
    let GithubErrorKind::Forbidden { credential } = &classified else {
        return classified;
    };
    let snap = rate_limit.snapshot().await;
    if snap.remaining != Some(0) {
        return classified;
    }
    let now = Utc::now();
    let reset = match snap.reset {
        Some(r) if r > now => r,
        _ => now + chrono::Duration::seconds(60),
    };
    GithubErrorKind::RateLimited {
        credential: credential.clone(),
        reset,
    }
}

/// Retry policy for `dispatch`: backon `ExponentialBuilder` with
/// rate-limit `retry_after` override via `.adjust()`. Returns the
/// final outcome or the terminal error.
///
/// Backoff is min_delay=5s, max_delay=5m, factor=2.0, jitter=true.
/// Permanent errors short-circuit via `.when()`; transient errors
/// retry per the schedule. RateLimited errors override the schedule
/// with the response's `Reset` epoch via `.adjust()` — the duration
/// returned by retry_after takes precedence over backon's computed
/// delay so the next attempt fires *after* the quota window opens
/// (we max() the two so we never poll *before*
/// reset).
pub async fn dispatch_with_retry(
    client: &Client,
    rate_bucket: Arc<RateBucket>,
    rate_limit: Arc<RateLimitState>,
    params: DispatchParams,
    max_attempts: u32,
    cancel: CancellationToken,
) -> Result<DispatchOutcome, GithubErrorKind> {
    let backoff = ExponentialBuilder::default()
        .with_min_delay(Duration::from_secs(5))
        .with_max_delay(Duration::from_secs(300))
        .with_factor(2.0)
        .with_jitter()
        .with_max_times(max_attempts as usize);

    (|| async {
        dispatch(
            client,
            rate_bucket.as_ref(),
            rate_limit.as_ref(),
            &params,
            &cancel,
        )
        .await
    })
    .retry(backoff)
    .when(GithubErrorKind::is_transient)
    // The adjust closure intentionally returns `Some(retry_after)`
    // when the schedule's `dur` is `None` (i.e. backon has exhausted
    // `max_attempts`) so a `RateLimited` response always honors the
    // server's `Retry-After` window even after the configured retry
    // budget would otherwise stop. This is deliberate: the server
    // told us the exact instant quota reopens, and a strict budget
    // cutoff would either thrash on 403/RateLimited or surface a
    // spurious "exhausted retries" error against the operator.
    // RateLimited is the ONLY kind whose `retry_after()` returns
    // `Some` (see `GithubErrorKind::retry_after`), so other
    // transient errors still respect `max_attempts` via backon's
    // returned `None`.
    .adjust(|err: &GithubErrorKind, dur: Option<Duration>| {
        // RateLimited overrides the schedule with the reset
        // epoch — but never *below* backon's computed delay
        // (otherwise a tight reset could starve other flows).
        match (err.retry_after(Utc::now()), dur) {
            (Some(retry_after), Some(d)) => Some(retry_after.max(d)),
            (Some(retry_after), None) => Some(retry_after),
            (None, dur) => dur,
        }
    })
    .notify(|err: &GithubErrorKind, dur: Duration| {
        warn!(error = %err, ?dur, "transient dispatch error; retrying");
    })
    .await
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn build_inputs_payload_injects_gcit_run_id() {
        let mut inputs = BTreeMap::new();
        inputs.insert("upstream_sha".to_string(), "deadbeef".to_string());
        let uuid = Uuid::nil();
        let v = build_inputs_payload(&inputs, uuid);
        let obj = v.as_object().expect("object");
        assert_eq!(obj.get("upstream_sha").unwrap(), "deadbeef");
        assert_eq!(
            obj.get("gcit_run_id").unwrap(),
            "00000000-0000-0000-0000-000000000000",
        );
        // Exactly two keys.
        assert_eq!(obj.len(), 2);
    }

    #[test]
    fn build_inputs_payload_injects_into_empty_inputs() {
        let inputs = BTreeMap::new();
        let uuid = Uuid::nil();
        let v = build_inputs_payload(&inputs, uuid);
        let obj = v.as_object().expect("object");
        assert!(obj.contains_key("gcit_run_id"));
        assert_eq!(obj.len(), 1);
    }

    #[test]
    fn build_inputs_payload_overwrites_user_supplied_gcit_run_id() {
        // Defensive: even if a user-supplied input named
        // "gcit_run_id" reaches this layer (config validation
        // should reject upstream), the injection wins.
        let mut inputs = BTreeMap::new();
        inputs.insert("gcit_run_id".to_string(), "user-supplied".to_string());
        let uuid = Uuid::from_u128(1);
        let v = build_inputs_payload(&inputs, uuid);
        let obj = v.as_object().expect("object");
        assert_eq!(
            obj.get("gcit_run_id").unwrap(),
            "00000000-0000-0000-0000-000000000001",
        );
    }

    #[test]
    fn split_repo_owner_and_name() {
        let (o, r) = split_repo("myorg/linux-builder").unwrap();
        assert_eq!(o, "myorg");
        assert_eq!(r, "linux-builder");
    }

    #[test]
    fn split_repo_rejects_no_slash() {
        assert!(matches!(
            split_repo("noslash"),
            Err(GithubErrorKind::Unknown { .. }),
        ));
    }

    #[test]
    fn split_repo_rejects_empty_owner_or_repo() {
        assert!(matches!(
            split_repo("/repo"),
            Err(GithubErrorKind::Unknown { .. }),
        ));
        assert!(matches!(
            split_repo("owner/"),
            Err(GithubErrorKind::Unknown { .. }),
        ));
    }

    #[test]
    fn split_repo_drops_extra_slashes_into_repo_part() {
        // splitn(2) puts everything after the first '/' into the
        // second piece. Defensive — config validation already
        // rejects multi-slash repos.
        let (o, r) = split_repo("owner/sub/repo").unwrap();
        assert_eq!(o, "owner");
        assert_eq!(r, "sub/repo");
    }

    #[test]
    fn render_inputs_substitutes_handlebars_variables() {
        use serde_json::json;
        let hb = crate::notify::strict_handlebars();
        let mut inputs = BTreeMap::new();
        inputs.insert("upstream_sha".to_string(), "{{source.sha}}".to_string());
        inputs.insert("ref_name".to_string(), "{{source.ref_name}}".to_string());
        let ctx = json!({
            "source": { "sha": "deadbeef", "ref_name": "refs/heads/main" }
        });
        let out = render_inputs(&inputs, &ctx, &hb).unwrap();
        assert_eq!(out["upstream_sha"], "deadbeef");
        assert_eq!(out["ref_name"], "refs/heads/main");
    }

    #[test]
    fn render_inputs_strict_mode_rejects_undefined_variable() {
        // strict_mode = true means {{undefined.var}} surfaces as
        // an error. The dispatcher should never see this in
        // practice (config validation registers every template
        // and renders it against a probe context), but we keep the
        // strict check active so a template change post-deploy
        // doesn't silently produce empty strings.
        use serde_json::json;
        let hb = crate::notify::strict_handlebars();
        let mut inputs = BTreeMap::new();
        inputs.insert("k".to_string(), "{{undefined}}".to_string());
        let ctx = json!({});
        let err = render_inputs(&inputs, &ctx, &hb).expect_err("strict_mode rejects");
        // RenderError carries the template name + variable name.
        let msg = format!("{err}");
        assert!(msg.contains("undefined"), "msg: {msg}");
    }

    #[test]
    fn gcit_run_id_input_constant_pinned() {
        // The workflow author writes `inputs.gcit_run_id`. Drift here
        // would silently break every deployment. Pin literal.
        assert_eq!(GCIT_RUN_ID_INPUT, "gcit_run_id");
    }
}
