// `gcit completions <SHELL>`.
//
// The completion script is generated by `clap_complete::generate`
// against the constructed `clap::Command`. We exercise the binary
// for each shell variant to confirm:
//   - exit code 0
//   - stdout is non-empty (a real completion script, not a stub)
//   - stdout contains "gcit" (the program name set by `set_bin_name`
//     in `clap_complete::generate`).

use assert_cmd::Command;
use predicates::prelude::*;

fn assert_completions_for_shell(shell: &str) {
    Command::cargo_bin("gcit")
        .unwrap()
        .args(["completions", shell])
        .assert()
        .success()
        .stdout(predicate::str::is_empty().not())
        .stdout(predicate::str::contains("gcit"));
}

#[test]
fn completions_bash() {
    assert_completions_for_shell("bash");
}

#[test]
fn completions_zsh() {
    assert_completions_for_shell("zsh");
}

#[test]
fn completions_fish() {
    assert_completions_for_shell("fish");
}

#[test]
fn completions_elvish() {
    assert_completions_for_shell("elvish");
}

#[test]
fn completions_powershell() {
    assert_completions_for_shell("powershell");
}

#[test]
fn completions_unknown_shell_exits_nonzero() {
    // clap rejects unknown values for `value_enum` arguments; the
    // exit code is clap's default (USAGE) — we only assert it is
    // non-zero so a future `Shell` enum addition or rename does not
    // break the test.
    Command::cargo_bin("gcit")
        .unwrap()
        .args(["completions", "bourne"])
        .assert()
        .failure();
}

#[test]
fn completions_bash_passes_bash_n_syntax_check() {
    // The bash completion script must parse cleanly under
    // `bash -n` (syntax-only, no execution). A truncated or
    // malformed script would surface here as a syntax error.
    //
    // Strategy: write the generated script to a tempfile then run
    // `bash -n <path>`. We avoid pipes for portability — older
    // assert_cmd versions do not handle stdin streaming uniformly.
    let out = Command::cargo_bin("gcit")
        .unwrap()
        .args(["completions", "bash"])
        .output()
        .expect("run gcit completions bash");
    assert!(out.status.success(), "gcit completions bash failed");
    let mut script = tempfile::NamedTempFile::new().expect("tempfile");
    use std::io::Write;
    script.write_all(&out.stdout).expect("write");
    script.flush().expect("flush");

    // Skip the test rather than fail when the host has no `bash` —
    // CI containers without bash installed would otherwise produce
    // a spurious failure. The runner reports the skip via stderr.
    let bash_check = std::process::Command::new("bash")
        .arg("-n")
        .arg(script.path())
        .output();
    let bash_check = match bash_check {
        Ok(o) => o,
        Err(e) if e.kind() == std::io::ErrorKind::NotFound => {
            eprintln!("test skipped: bash not available on PATH");
            return;
        }
        Err(e) => panic!("failed to spawn bash: {e}"),
    };
    assert!(
        bash_check.status.success(),
        "bash -n rejected the generated completion script:\nstderr={}",
        String::from_utf8_lossy(&bash_check.stderr),
    );
}
